###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
##
##============================================================================================
## DISCLAIMER
## These configurations are not indicated or intended to be valid for production environments.
## The purpose is purely educational.
##============================================================================================
##
## DEPLOYMENT CONTENTS
## 
## patterns: starter, authoring, bai
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: ${CP4BA_INST_CR_NAME}
  namespace: ${CP4BA_INST_NAMESPACE}
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: "23.0.2"
  annotations:
    kubernetes.io/description: "${CP4BA_INST_DESCRIPTION}"
spec:

  appVersion: "23.0.2"
  ibm_license: accept

  bai_configuration:
    business_performance_center:
      all_users_access: true

  bastudio_configuration:
    kafka_services:
      enabled: true
    database:
      cm_max_pool_size: ${CP4BA_INST_BASTUDIO_DB_MIN_POOL}
      cm_min_pool_size: ${CP4BA_INST_BASTUDIO_DB_MAX_POOL}
    resources:
      bastudio:
        limits:          
          cpu: '${CP4BA_INST_BASTUDIO_LIMITS_CPU}'
          memory: ${CP4BA_INST_BASTUDIO_LIMITS_MEM}

  shared_configuration:
    enable_fips: false
    sc_deployment_type: Starter
    sc_deployment_patterns: "${CP4BA_INST_DEPL_PATTERNS}"
    sc_optional_components: "${CP4BA_INST_OPT_COMPONENTS}"
    sc_iam:
      default_admin_username: ''
    sc_drivers_url: null
    image_pull_secrets:
      - ibm-entitlement-key
    trusted_certificate_list: []
    sc_deployment_baw_license: non-production
    storage_configuration:
      sc_dynamic_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_slow_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_medium_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_fast_file_storage_classname: "${CP4BA_INST_SC_FILE}"
      sc_block_storage_classname: "${CP4BA_INST_SC_BLOCK}"
    root_ca_secret: '{{ meta.name }}-root-ca'
    sc_content_initialization: true
    sc_deployment_license: non-production
    sc_egress_configuration:
      sc_api_namespace: null
      sc_api_port: null
      sc_dns_namespace: null
      sc_dns_port: null
      sc_restricted_internet_access: false
    sc_ingress_enable: false
    sc_image_repository: cp.icr.io
    sc_deployment_platform: OCP
    sc_deployment_fncm_license: non-production
